[project]
name = "qrcode-generator"
version = "0.1.0"
description = "Cross-platform QR code generator with CLI and GUI"
authors = [
    { name="Pierre Lacerte" }
]
readme = "README.md"
requires-python = ">=3.8"
